import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Header from '@/components/common/header'

const montserrat = Montserrat({ subsets: ['latin'], weight: ["400", "600", "700"] })

export const metadata: Metadata = {
  title: 'Hydra',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`${montserrat.className} bg-primary-color`}>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
